In [3]:
import os
import sys

In [10]:
임대_dict= {'단독다가구_임대' : 'house_lease.db',
      '아파트_임대' : 'apt_lease.db',
      '연립다세대_임대': 'multi-family_lease.db',
      '오피스텔_임대': 'house_lease.db'
      }

base_url = '/Users/hj/Dropbox/real_estate/data/임대'

from sqlalchemy import create_engine
import pandas as pd
for dir_name, db_name in 임대_dict.items() :
    data_dir = os.path.join(base_url, dir_name)
    db_path = os.path.join(data_dir, db_name)
    tab_name = db_name.split('.')[0]
    eng = create_engine(f"sqlite:///{db_path}")
    for year in range(2006, 2025):
        year_dir = os.path.join(data_dir, str(year))
        if not os.path.exists(year_dir):
            os.makedirs(year_dir)
        for month in range(1, 13):
            df = pd.read_sql(f"SELECT * FROM {tab_name} WHERE 년 = {year} AND 월 = {month}", con = eng)
            file_name = os.path.join(year_dir, f"{dir_name}_{year}년_{month:02}월.csv")
            df.to_csv(file_name, index = False)
        print(f"{dir_name} {year}년 저장완료")

OperationalError: (sqlite3.OperationalError) no such table: house_lease
[SQL: SELECT * FROM house_lease WHERE 년 = 2006 AND 월 = 1]
(Background on this error at: https://sqlalche.me/e/20/e3q8)